name: Android SDL Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - uses: actions/checkout@v3

      # 下载并解压 Android NDK（Google 官方镜像）
      - name: Install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip -d $HOME
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-r25c" >> $GITHUB_ENV

      # 配置 CMake 并编译 SDL
      - name: Configure & Build SDL
        run: |
          cmake -S . -B build \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21
          cmake --build build --parallel

      # 打包编译产物（比如 .so/.apk）
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SDL-build
          path: build/
